household/urls.py
#coding:utf-8
from django.conf.urls import patterns, include, url
from calc.views import *
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'household.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),

    url(r'^accounts/login/$', login, {'template_name': 'login.html'}),
    url(r'^accounts/logout/$', logout),
    url(r'^password/change/$', password_change, {'template_name': 'password.html'}),

    url(r'^$', index),
    url(r'^spend/list/$', spend_list, {'template_name': 'spend/spend_list.html'}),
    url(r'^spend/add/$', spend_add, {'template_name': 'spend/spend_form.html'}),
    url(r'^spend/delete/(?P<pk>\d+)/$', spend_delete),
    url(r'^spend/calc/$', spend_calc),
    url(r'^calc/list/$', calc_list, {'template_name': 'calc/calc_list.html'}),
    url(r'^bill/list/$', bill_list, {'template_name': 'bill/bill_list.html'}),
    url(r'^bill/details/(?P<pk>\w+)/$', bill_details, {'template_name': 'bill/bill_details.html'}),

)

calc/models.py
#coding:utf-8
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User

SPENDING_STATUS_CHOICES = (
    (0, u'开支'),
    (1, u'已结算'),
)


class Spending(models.Model):
    amount = models.FloatField(u'金额')
    payer = models.ForeignKey(User, verbose_name=u'付款人', related_name='payer_user')
    members = models.ManyToManyField(User, verbose_name=u'成员', related_name='members_users')
    spendTime = models.DateTimeField(u'开支时间', default=datetime.now())
    status = models.IntegerField(u'状态', default=0, choices=SPENDING_STATUS_CHOICES)
    calcId = models.CharField(u'结算编号', max_length=50, blank=True)
    note = models.TextField(u'备注')
    createTime = models.DateTimeField(u'创建时间', auto_now_add=True)
    updateTime = models.DateTimeField(u'修改时间', auto_now=True)

    class Meta:
        db_table = 'household_calc_spending'
        verbose_name = u'开支明细'
        verbose_name_plural = u'开支明细'


class Calculate(models.Model):
    id = models.CharField(u'结算编号', max_length=50, primary_key=True)
    totalAmount = models.FloatField(u'总金额', default=0)
    user = models.ForeignKey(User, verbose_name=u'结算人', related_name='calc_user')
    createTime = models.DateTimeField(u'结算时间', auto_now_add=True)

    class Meta:
        db_table = 'household_calc_calculate'
        verbose_name = u'结算记录'
        verbose_name_plural = u'结算记录'


class Bill(models.Model):
    calc = models.ForeignKey(Calculate, verbose_name=u'结算编号', related_name='bill_calc')
    user = models.ForeignKey(User, verbose_name=u'成员', related_name='bill_user')
    amount = models.FloatField(u'金额', default=0)
    expense = models.FloatField(u'总消费', default=0)
    pay = models.FloatField(u'总付款', default=0)
    createTime = models.DateTimeField(u'创建时间', auto_now_add=True)

    class Meta:
        db_table = 'household_calc_bill'
        unique_together = ('calc', 'user')
        verbose_name = u'账单'
        verbose_name_plural = u'账单'

calc/forms.py
#coding:utf-8

from django import forms
from .models import *


class SpendForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(SpendForm, self).__init__(*args, **kwargs)
        for field in self:
            field.field.widget.attrs.update({'class': 'form-control'})

    class Meta:
        model = Spending
        exclude = ('calcId',)


class SpendQueryForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(SpendQueryForm, self).__init__(*args, **kwargs)
        for field in self:
            field.field.widget.attrs.update({'class': 'form-control'})

    class Meta:
        model = Spending
        fields = ('payer', 'status', 'calcId')


class PasswordForm(forms.Form):

    def __init__(self, *args, **kwargs):
        super(PasswordForm, self).__init__(*args, **kwargs)
        for field in self:
            field.field.widget.attrs.update({'class': 'form-control'})

    password = forms.CharField(label="原密码", required=True)
    password1 = forms.CharField(label="新密码", required=True)
    password2 = forms.CharField(label="确认密码", required=True)

calc/views.py
#coding:utf-8
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.contrib.auth import logout as auth_logout
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import login as auth_login
from django.shortcuts import render_to_response, get_object_or_404
from .utils import list_items, del_item, gen_serial_no
from .models import *
from .forms import *
import json
from django.db import transaction
import logging
logger = logging.getLogger('django.request')


def login(request, template_name):
    return auth_login(request, template_name)


def logout(request):
    auth_logout(request)
    return HttpResponseRedirect("/")


@login_required
@csrf_exempt
def password_change(request, template_name):
    if request.method == "GET":
        form = PasswordForm()
        return render_to_response(template_name, locals())
    if request.method == "POST":
        form = PasswordForm(request.POST)
        if form.is_valid():
            user = request.user
            password = form.cleaned_data['password']
            if not user.check_password(password):
                info = "原密码错误！"
                return render_to_response(template_name, locals())
            password1 = form.cleaned_data['password1']
            password2 = form.cleaned_data['password2']
            if password1 != password2:
                info = "两次输入密码不一致！"
                return render_to_response(template_name, locals())
            user.set_password(password1)
            user.save()
            info = "密码修改成功！"
        else:
            errors = form.errors
        return render_to_response(template_name, locals())


@login_required
def index(request):
    if request.user.is_authenticated():
        return HttpResponseRedirect(reverse('calc.views.spend_list'))
    return HttpResponseRedirect("/accounts/login/")


@login_required
@csrf_exempt
def spend_list(request, template_name):
    spends = Spending.objects.all()
    if request.method == "GET":
        form = SpendQueryForm()
        spends = spends.filter(status=0)
    elif request.method == "POST":
        form = SpendQueryForm(request.POST)
        payer = request.POST.get('payer')
        status = request.POST.get('status')
        calc_id = request.POST.get('calcId')
        if payer:
            spends = spends.filter(payer__id=payer)
        if status:
            spends = spends.filter(status=status)
        if calc_id:
            spends = spends.filter(calcId=calc_id)
    page, page_size = list_items(request, spends)
    return render_to_response(template_name, locals())


@login_required
@csrf_exempt
def spend_add(request, template_name):
    if request.method == "GET":
        form = SpendForm()
    elif request.method == "POST":
        form = SpendForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('calc.views.spend_list'))
        else:
            errors = form.errors
    return render_to_response(template_name, locals())


@login_required
def spend_delete(request, pk):
    return del_item(Spending, pk)


@login_required
@csrf_exempt
@transaction.commit_manually
def spend_calc(request):
    if request.method == "POST":
        try:
            spend_ids = request.REQUEST.getlist('spend_id')
            spends = Spending.objects.filter(id__in=spend_ids)
            total_mount = 0
            serial_no = gen_serial_no()
            #累计成员消费金额
            expense_dict = {}
            #累计成员付款金额
            pay_dict = {}
            #累计结算结果金额
            amount_dict = {}
            for spend in spends:
                amount = spend.amount
                payer = spend.payer
                #累计付款人的支付金额
                pay_money = pay_dict.get(payer, 0)
                pay_money += amount
                pay_dict[payer] = pay_money

                #累计支付总额
                total_mount += amount
                #计算成员的平均消费
                members = spend.members.all()
                size = len(members)
                ave_money = round(amount / size, 2)
                #累计成员的消费金额
                for m in members:
                    m_exp = expense_dict.get(m, 0)
                    m_exp += ave_money
                    expense_dict[m] = m_exp
                    #计算消费金额
                    u_exp_money = amount_dict.get(m, 0)
                    u_exp_money += ave_money
                    amount_dict[m] = u_exp_money
                    #m.bill_user.add()
                amount_dict[payer] = amount_dict.get(payer, 0) - amount
                spend.status = 1
                spend.calcId = serial_no
                spend.save()
            calculate = Calculate(
                id=serial_no,
                totalAmount=total_mount,
                user=request.user
            )
            calculate.save()
            for u, exp in expense_dict.items():
                bill = Bill(
                    calc=calculate,
                    user=u,
                    amount=amount_dict.get(u, 0),
                    expense=exp,
                    pay=pay_dict.get(u, 0)
                )
                bill.save()
        except Exception, e:
            transaction.rollback()
            logger.error(e, exc_info=e)
            resp = json.dumps({"state": 0, "msg": "系统异常，结算失败"})
            return HttpResponse(resp, content_type="application/json")
        else:
            transaction.commit()
            # resp = json.dumps({"state": 1, "msg": "成功"})
    return HttpResponseRedirect(reverse('calc.views.bill_details', args=(serial_no,)))


@login_required
def calc_list(request, template_name):
    page, page_size = list_items(request, Calculate.objects.all())
    return render_to_response(template_name, locals())


@login_required
def bill_list(request, template_name):
    page, page_size = list_items(request, Bill.objects.all())
    return render_to_response(template_name, locals())


@login_required
def bill_details(request, pk, template_name):
    calculate = Calculate.objects.filter(id=pk)[0]
    bills = Bill.objects.filter(calc__id=pk)
    page, page_size = list_items(request, Spending.objects.filter(calcId=pk))
    return render_to_response(template_name, locals())

calc/templates/spend/spend_form.html
{% extends "base.html" %}

{% block extrahead %}
    {% load static from staticfiles %}
    <script src="{% static "js/My97DatePicker/WdatePicker.js" %}"></script>
    <script>
        $(function() {
            $("#id_spendTime").attr({"onFocus": "WdatePicker({dateFmt:'yyyy-MM-dd HH:mm:ss'})", "placeholder": "请选择时间"});
            $("#id_amount").attr({"placeholder": "人民币 元"});
            $("#id_note").attr({"placeholder": "开支说明"});
        });
    </script>
{% endblock %}

{% block content %}
    <section class="content-header">
        <h1>开支明细管理</h1>
    </section>
    <section class="content">
        <div class="box">
            <div class="box-header">
                <h3 class="box-title">添加开支信息</h3>
            </div>
            <div class="box-body">
                <form class="form-horizontal" method="POST">
                    {% for field in form %}
                        <div class="form-group">
                            {{ field.errors }}
                            <label class="col-sm-2 control-label" for="{{ field.id_for_label }}">{{ field.label }}</label>
                            <div class="col-sm-6">
                                {{ field }}
                            </div>
                        </div>
                    {% endfor %}
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-6">
                            <input type="submit" class="btn btn-primary" value="提交" />
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </section>
{% endblock %}

calc/templates/spend/spend_list.html
{% extends "base.html" %}

{% block extrahead %}
    <script>
        $(function() {
            $("#id_calcId").attr({"placeholder": "结算编号"});

            $("#id_spend_all").click(function(){
                var flag = this.checked;
                $('[name=spend_id]:checkbox').each(function(){
                    this.checked = flag;
                });
            });

            $('[name=spend_id]:checkbox').click(function(){
                var flag = true;
                $('[name=spend_id]:checkbox').each(function(){
                    if(!this.checked){
                        flag = false;
                    }
                });
                $("#id_spend_all").each(function(){
                    this.checked = flag;
                });
            });

            $("#btn_spend_calc").click(function(){
                var flag = false;
                $('[name=spend_id]:checkbox').each(function(){
                    if(this.checked){
                        flag = true;
                    }
                });
                if(!flag){
                    alert("请至少选择一条记录！");
                    return false;
                }
                $("#spend_form").submit();
            });
        });
    </script>
{% endblock %}

{% block content %}
    <section class="content-header">
        <h1>开支明细管理</h1>
    </section>
    <section class="content">
        <a href="{% url 'calc.views.spend_add' %}" class="new btn btn-primary">新增</a>
        <div class="box">
            <div class="box-header">
                <form id="spend_query" method="post" action="{% url 'calc.views.spend_list' %}" class="form-inline">
                    <div class="form-group">
                        {% for field in form %}
                            {{ field }}
                        {% endfor %}
                        <input type="submit" class="btn btn-success" value="查询">
                    </div>
                </form>
            </div>
            <div class="box-body">
                {% include 'page/header.html'%}
                <form id="spend_form" method="post" action="{% url 'calc.views.spend_calc' %}">
                    <div class="horizontal-scroll">
                        <table class="table table-striped table-bordered table-hover">
                            <thead>
                                <tr>
                                    <th></th>
                                    <th>付款人</th>
                                    <th>金额</th>
                                    <th>成员</th>
                                    <th>开支时间</th>
                                    <th>状态</th>
                                    <th>结算编号</th>
                                    <th>备注</th>
                                    <th>创建时间</th>
                                    <th>修改时间</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for spend in page %}
                                <tr>
                                    <td><input type="checkbox" name="spend_id" value="{{ spend.pk }}"></td>
                                    <td>{{ spend.payer }}</td>
                                    <td>{{ spend.amount }}</td>
                                    <td>
                                        {% for m in spend.members.all %}
                                            {% if not forloop.first %}, {% endif %} {{ m }}
                                        {% endfor %}
                                    </td>
                                    <td>{{ spend.spendTime|date:"Y-m-d H:i" }}</td>
                                    <td>{{ spend.get_status_display }}</td>
                                    <td>{% if spend.calcId %}<a href="{% url 'calc.views.bill_details' pk=spend.calcId %}">{{ spend.calcId }}</a>{% endif %}</td>
                                    <td>{{ spend.note }}</td>
                                    <td>{{ spend.createTime|date:"Y-m-d H:i" }}</td>
                                    <td>{{ spend.updateTime|date:"Y-m-d H:i" }}</td>
                                    <td><a href="{% url 'calc.views.spend_delete' pk=spend.pk %}" class="delete">删除</a> </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                            <tfoot>
                                <tr>
                                    <th><input type="checkbox" id="id_spend_all"></th>
                                    <th colspan="10">
                                        <input type="button" id="btn_spend_calc" class="new btn btn-primary" value="结算">
                                    </th>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                </form>
                {% include "page/content.html" %}
            </div>
        </div>
    </section>

{% endblock %}